int32 batchsize
float32[] cur_vel 
float32[] tensor
float32[] semantic_tensor 
string mode
---
float32[] value
float32[] acc_pi
float32[] acc_mu
float32[] acc_sigma
float32[] ang
float32[] vel_pi
float32[] vel_mu
float32[] vel_sigma
float32[] lane
