FROM melodic_cuda10_1_cudnn7_libtorch_opencv4
 
USER root
WORKDIR /root

RUN mkdir -p catkin_ws/src

RUN apt-get -y update
RUN apt-get -y install vim

RUN rm -rf /var/lib/apt/lists/*

RUN cd catkin_ws/src
COPY catkin_ws/src catkin_ws/

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]

